# Titanicのデータでfeaturetoolsを試す

In [1]:
import featuretools
import pandas as pd

In [2]:
train = pd.read_csv('../input/train.csv')
train = train.drop('Survived', 1)

# EntitySetの準備をする

In [3]:
es: featuretools.entityset.entityset.EntitySet

es = featuretools.EntitySet(id='data')

es.entity_from_dataframe(entity_id='train',
                         dataframe=train,
                         index='PassengerId')

Entityset: data
  Entities:
    train [Rows: 891, Columns: 11]
  Relationships:
    No relationships

# 利用可能なPrimitiveを見る

In [4]:
p = featuretools.list_primitives()

In [5]:
p[p['type'] == 'transform']

,name,type,description
20,time_since,transform,Calculates time from a value to a specified cu...
21,divide_by_feature,transform,Divide a scalar by each value in the list.
22,day,transform,Determines the day of the month from a datetime.
23,greater_than,transform,Determines if values in one list are greater t...
24,less_than,transform,Determines if values in one list are less than...
25,haversine,transform,Calculates the approximate haversine distance ...
26,add_numeric_scalar,transform,Add a scalar to each value in the list.
27,num_characters,transform,Calculates the number of characters in a string.
28,time_since_previous,transform,Compute the time since the previous entry in a...
29,cum_min,transform,Calculates the cumulative minimum.
30,latitude,transform,Returns the first tuple value in a list of Lat...
31,not_equal_scalar,transform,Determines if values in a list are not equal t...
32,is_weekend,transform,Determines if a date falls on a weekend.
33,cum_count,transform,Calculates the cumulative count.
34,not,transform,Negates a boolean value.
35,equal_scalar,transform,Determines if values in a list are equal to a ...
36,month,transform,Determines the month value of a datetime.
37,or,transform,Element-wise logical OR of two lists.
38,multiply_numeric_scalar,transform,Multiply each element in the list by a scalar.
39,diff,transform,Compute the difference between the value in a ...
40,greater_than_equal_to_scalar,transform,Determines if values are greater than or equal...
41,less_than_equal_to_scalar,transform,Determines if values are less than or equal to...
42,minute,transform,Determines the minutes value of a datetime.
43,modulo_by_feature,transform,Return the modulo of a scalar by each element ...
44,absolute,transform,Computes the absolute value of a number.
45,scalar_subtract_numeric_feature,transform,Subtract each value in the list from a given s...
46,days_since,transform,Calculates the number of days from a value to ...
47,greater_than_scalar,transform,Determines if values are greater than a given ...
48,hour,transform,Determines the hour value of a datetime.
49,less_than_scalar,transform,Determines if values are less than a given sca...
50,modulo_numeric,transform,Element-wise modulo of two lists.
51,subtract_numeric,transform,Element-wise subtraction of two lists.
52,num_words,transform,Determines the number of words in a string by ...
53,divide_numeric_scalar,transform,Divide each element in the list by a scalar.
54,is_null,transform,Determines if a value is null.
55,cum_max,transform,Calculates the cumulative maximum.
56,longitude,transform,Returns the second tuple value in a list of La...
57,add_numeric,transform,Element-wise addition of two lists.
58,weekday,transform,Determines the day of the week from a datetime.
59,cum_mean,transform,Calculates the cumulative mean.
60,percentile,transform,Determines the percentile rank for each value ...
61,not_equal,transform,Determines if values in one list are not equal...
62,year,transform,Determines the year value of a datetime.
63,cum_sum,transform,Calculates the cumulative sum.
64,divide_numeric,transform,Element-wise division of two lists.
65,and,transform,Element-wise logical AND of two lists.
66,equal,transform,Determines if values in one list are equal to ...
67,negate,transform,Negates a numeric value.
68,week,transform,Determines the week of the year from a datetime.
69,multiply_numeric,transform,Element-wise multiplication of two lists.
70,isin,transform,Determines whether a value is present in a pro...
71,greater_than_equal_to,transform,Determines if values in one list are greater t...
72,less_than_equal_to,transform,Determines if values in one list are less than...
73,modulo_numeric_scalar,transform,Return the modulo of each element in the list ...
74,second,transform,Determines the seconds value of a datetime.
75,subtract_numeric_scalar,transform,Subtract a scalar from each element in the list.

In [6]:
# いじりやすいようにソートした
p[p['type'] == 'transform'].sort_values('name').name.values

array(['absolute', 'add_numeric', 'add_numeric_scalar', 'and',
       'cum_count', 'cum_max', 'cum_mean', 'cum_min', 'cum_sum', 'day',
       'days_since', 'diff', 'divide_by_feature', 'divide_numeric',
       'divide_numeric_scalar', 'equal', 'equal_scalar', 'greater_than',
       'greater_than_equal_to', 'greater_than_equal_to_scalar',
       'greater_than_scalar', 'haversine', 'hour', 'is_null',
       'is_weekend', 'isin', 'latitude', 'less_than',
       'less_than_equal_to', 'less_than_equal_to_scalar',
       'less_than_scalar', 'longitude', 'minute', 'modulo_by_feature',
       'modulo_numeric', 'modulo_numeric_scalar', 'month',
       'multiply_numeric', 'multiply_numeric_scalar', 'negate', 'not',
       'not_equal', 'not_equal_scalar', 'num_characters', 'num_words',
       'or', 'percentile', 'scalar_subtract_numeric_feature', 'second',
       'subtract_numeric', 'subtract_numeric_scalar', 'time_since',
       'time_since_previous', 'week', 'weekday', 'year'], dtype=object)

# どんな特徴量が生成されるかを試す

In [7]:
# コメント解除したりして試せるよ

trans = [
#'absolute',
 'add_numeric',
# 'add_numeric_scalar',
# 'and', # いれても意味無い
# 'cum_count',
# 'cum_max',
# 'cum_mean',
# 'cum_min',
# 'cum_sum',
# 'day',
# 'days_since',
# 'diff',
# 'divide_by_feature',
# 'divide_numeric',
# 'divide_numeric_scalar',
# 'equal',
# 'equal_scalar',
# 'greater_than',
# 'greater_than_equal_to',
# 'greater_than_equal_to_scalar',
# 'greater_than_scalar',
# 'haversine',
# 'hour',
# 'is_null',
# 'is_weekend',
# 'isin',
# 'latitude',
# 'less_than',
# 'less_than_equal_to',
# 'less_than_equal_to_scalar',
# 'less_than_scalar',
# 'longitude',
# 'minute',
# 'modulo_by_feature',
# 'modulo_numeric',
# 'modulo_numeric_scalar',
# 'month',
# 'multiply_numeric',
# 'multiply_numeric_scalar',
# 'negate',
# 'not',
# 'not_equal',
# 'not_equal_scalar',
# 'num_characters',
# 'num_words',
# 'or',
# 'percentile',
# 'scalar_subtract_numeric_feature',
# 'second',
# 'subtract_numeric',
# 'subtract_numeric_scalar',
# 'time_since',
# 'time_since_previous',
# 'week',
# 'weekday',
# 'year'
]


feature_names = featuretools.dfs(entityset=es,
                                 target_entity='train',
                                 verbose=1,
                                 agg_primitives=[],
                                 trans_primitives=trans,
                                 features_only=True,
                                 max_depth=1
                                 )
feature_names

Built 20 features

[<Feature: Pclass>,
 <Feature: Name>,
 <Feature: Sex>,
 <Feature: Age>,
 <Feature: SibSp>,
 <Feature: Parch>,
 <Feature: Ticket>,
 <Feature: Fare>,
 <Feature: Cabin>,
 <Feature: Embarked>,
 <Feature: Pclass + SibSp>,
 <Feature: Age + Fare>,
 <Feature: Fare + Pclass>,
 <Feature: Parch + Pclass>,
 <Feature: Age + Pclass>,
 <Feature: Fare + Parch>,
 <Feature: Parch + SibSp>,
 <Feature: Age + Parch>,
 <Feature: Age + SibSp>,
 <Feature: Fare + SibSp>]

# 実際に特徴量を作って、処理時間と結果を見る

In [8]:
df, fs = featuretools.dfs(entityset=es,
                         target_entity='train',
                         verbose=1,
                         agg_primitives=[],
                         trans_primitives=trans,
                         features_only=False,
                         max_depth=1
                         )

Built 20 features
Elapsed: 00:00 | Remaining: 00:00 | Progress: 100%|██████████| Calculated: 11/11 chunks

In [9]:
df.head()

,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Pclass + SibSp,Age + Fare,Fare + Pclass,Parch + Pclass,Age + Pclass,Fare + Parch,Parch + SibSp,Age + Parch,Age + SibSp,Fare + SibSp
PassengerId,,,,,,,,,,,,,,,,,,,,
1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,4,29.2500,10.2500,3,25.0,7.2500,1,22.0,23.0,8.2500
2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,109.2833,72.2833,1,39.0,71.2833,1,38.0,39.0,72.2833
3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,3,33.9250,10.9250,3,29.0,7.9250,0,26.0,26.0,7.9250
4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2,88.1000,54.1000,1,36.0,53.1000,1,35.0,36.0,54.1000
5,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,3,43.0500,11.0500,3,38.0,8.0500,0,35.0,35.0,8.0500

In [10]:
fs

[<Feature: Pclass>,
 <Feature: Name>,
 <Feature: Sex>,
 <Feature: Age>,
 <Feature: SibSp>,
 <Feature: Parch>,
 <Feature: Ticket>,
 <Feature: Fare>,
 <Feature: Cabin>,
 <Feature: Embarked>,
 <Feature: Pclass + SibSp>,
 <Feature: Age + Fare>,
 <Feature: Fare + Pclass>,
 <Feature: Parch + Pclass>,
 <Feature: Age + Pclass>,
 <Feature: Fare + Parch>,
 <Feature: Parch + SibSp>,
 <Feature: Age + Parch>,
 <Feature: Age + SibSp>,
 <Feature: Fare + SibSp>]

# おわりに
- 1テーブルでも活用の道はありそう
- 意味のある集約計算と意味のない集約計算(今回だとand)があるので、よくみたほうがいいね